#!/bin/bash

# exit if any error occurs
set -o errexit
# exit if any pipe commands fails
set -o pipefail
# exit if any variable is not set
set -o nounset

python manage.py makemigrations --no-input
python manage.py migrate --no-input
python manage.py collectstatic --no-input
python manage.py runserver 0.0.0.0:8000