# Generated by Django 4.1.6 on 2023-02-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pkid',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
