# Generated by Django 4.1.6 on 2023-02-21 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8d468cf0-54ad-41b6-93bd-e22913c745e0'), editable=False, unique=True),
        ),
    ]
