# Generated by Django 4.1.6 on 2023-02-22 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e779664c-bc9c-405f-ac3f-71c1b22f359f'), editable=False, unique=True),
        ),
    ]
