# Generated by Django 4.1.6 on 2023-03-04 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b289ae83-9d37-4411-bf01-0edde54ea958'), editable=False, unique=True),
        ),
    ]
